### ISSUE TITLE
add_exp may make the wrong assumptions.

### ISSUE THREAD

**Issue by ghost** [optimizely/chord#1]
```
// Computes a new key equal to key + 2 ^ exponent.
// Assumes key is a 4 element array of 32 bit words, most significant word first.
```

Try creating a few hashes with small string lengths up to 4, only the first word of the hash will be effected.  Then try hashing string lengths up to 8, only the first two words will be effected.

**Comment by bollenberger** [comment]
Hi there. I think this is the behavior of MurmurHash. It's definitely not a cryptographic hash (and if this concerns you, you could swap it for SHA256 or something pretty easily). Which assumption do you think this breaks? It is still a 4 element array of 32 bit works, most significant word first, right?

**Comment by ghost** [comment]
Since you are using the x86 (little endian) version of the 128 bit variant
of murmurhash I believe that the least significant bit would come first.

**Comment by bollenberger** [comment]
I guess this comes down to which byte we consider "most significant". If we're hashing small values, and the the first word is the only one that is changing, then I think we want to treat that word as the most significant, regardless of how Murmurhash treats it internally (is the first 32 bit word most or least significant in that implementation?). If that documentation is unclear or ambiguous, perhaps there's another way to refer to the first word in the hash. I'm open to suggestions.

**Comment by ghost** [comment]
It doesn't make a difference one way or the other.  Your functions will
still iterate through the entire keyspace.

I'll resolve the issue on github.
